price_hunter_index:
    path:     /{page}
    defaults: { _controller: "AlbAppBundle:PriceHunter:index", page: 1 }
    methods:  GET
    requirements:
        page: \d+

price_hunter_json:
    path:     /price-hunter/products.json
    defaults: { _controller: "AlbAppBundle:PriceHunter:json" }
    methods:  GET

price_hunter_import_products:
    path:     /full-import
    defaults: { _controller: "AlbAppBundle:PriceHunter:fullImport" }
    methods:  GET
price_hunter_search_products:
    path:     /search/{page}
    defaults: { _controller: "AlbAppBundle:PriceHunter:searchProducts", page: 1 }
    methods:  GET
