Alb\Bundle\AppBundle\Entity\Story:
    image:
        mapping:           story_image # required
        filename_property: imageName # required
        size:              imageSize
        mime_type:         imageMimeType
        original_name:     imageOriginalName