alb_app:
    resource: "@AlbAppBundle/Resources/config/routing.yml"
    prefix:   /

alb_frontend:
    resource: "@AlbFrontendBundle/Resources/config/routing.yml"
    prefix:   /

alb_backend:
    resource: "@AlbBackendBundle/Resources/config/routing.yml"
    prefix:   /backend

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
