# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    app.path.story_images: '%story_upload_destination%'

services:
    gedmo.listener.blameable:
        class: Gedmo\Blameable\BlameableListener
        tags:
          - { name: doctrine.event_subscriber, connection: default }
    
    alb_app.namer.story_upload:
        class: Alb\Bundle\AppBundle\Namer\StoryNamer
        tags:
            - { name: namer }
        arguments: [~, Alb\Bundle\AppBundle\Entity\Story, ~]

