# src/Alb/AppBundle/Resources/config/doctrine/PriceHunter.orm.yml
Alb\Bundle\AppBundle\Entity\PriceHunter:
    type: entity
    table: price_hunter
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        price:
            type: float
        price_min:
            type: float
        price_max:
            type: float
        link:
            type: string
            length: 255
        date:
            type: datetime
        image:
            nullable: true
            type: string
            options:
                default: 'noimage.jpg'
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
