# src/Alb/AppBundle/Resources/config/doctrine/Story.orm.yml
Alb\Bundle\AppBundle\Entity\Story:
    type: entity
    table: story
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        video:
            type: string
            length: 255
        image:
            nullable: true
            type: string
            options:
                default: 'maxresdefault.jpg'
        content:
            type: text
        language:
            nullable: true
            type: string
            length: 100
        recommended_age:
            nullable: true
            type: string
            length: 255
        type:
            nullable: true
            type: string
            length: 200
        genre:
            nullable: true
            type: string
            length: 255
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
